server:
  port: 8001

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.96.50.240:3307/newcloud?
    username: root
    password: liyuqi0709
#    url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.17.202.8)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 172.17.202.6)(PORT = 1521))(ADDRESS =(PROTOCOL = TCP)(HOST = 172.17.202.4)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 172.17.202.2)(PORT = 1521)))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = wlgjdb2)))
#      #url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.213.14.158)(PORT = 1521)))(CONNECT_DATA =(SERVICE_NAME = eomst)))
#      #username: sb_net
#      #password: SD!eoms3
#    username: netmanage_sd
#    password: Wlgej_Ins!4s
#    driver-class-name: oracle.jdbc.OracleDriver

mybatis:
   mapperLocations: classpath:mapper/*.xml
   type-aliases-package: com.liyuqi.entities
